name: Host App

on:
  push:
    paths:
      - 'host/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      # - name: Get pnpm store path
      #   shell: bash
      #   run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      # - name: Enable pnpm caching
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{ env.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: ${{ runner.os }}-pnpm-store-
      # - name: Enable Rust caching
      #   uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          pnpm install
          pnpm build
        working-directory: host
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: host
          path: |
            target/release/bundle/
            target/release/host
            target/release/host.*
